### ISSUE TITLE
Add Node option in the actual node list

### ISSUE THREAD

**Issue by pir8radio** [signum-network/signum-xt-wallet#13]
I know you can manually add your own wallet node to the XT wallet, but for noobs its hard to find that setting...    I suggest (especially with the potential for SIP-35) that we add an option at the top or bottom of the below list to "Manually Add" a node..    all this option would do is take the user directly to the /settings/networks page so they can manually add the node.  

![image](https://user-images.githubusercontent.com/16748696/153730005-f4e9e22e-28f7-498a-81e8-3cb7b3d30832.png)

**Comment by alicks** [comment]
Hi. I would like to add - related to the Topic:
1. if i want to add full URL: **http://**1.2.3.4:6876 - Wallet says - not valid URL. So, address only without HTTP looks is OK. But some of Signum nodes might use HTTPS for API, hence, HTTP (or HTTPS) is needed and a right format for URL.
![image](https://user-images.githubusercontent.com/10243140/153758370-75582751-ea5a-48cb-9643-d54e390f6b50.png)

2. I was trying adding my other testnet node located in my LAN - no success, so far.. Neither node in my LAN (private) IP, nor the same node via External (public) IP - **Cannot reach network node.**
![image](https://user-images.githubusercontent.com/10243140/153758581-60082473-9317-4441-814a-2e87269ed3c3.png)
