### ISSUE TITLE
Commited SIGNA amount considered as available Wallet balance

### ISSUE THREAD

**Issue by alicks** [signum-network/signum-xt-wallet#14]
**Is your feature request related to a problem? Please describe.**
I.e.: I have 210 signa and 200 of those are staked for Commitment. Hence, i have only 10 signa that i can operate with.
If i want send i.e. 30 signa - it shows an errors, that are, basically, hardly related to real reason.. 
See screenshot.
So, i have to remember how many Signa i have for Transactions and how many staken for Commitnent.

**Describe the solution you'd like**
If possible - separate Commited amount and Free amount of signa in Wallet. So, only Free signa have possibility to operate with in Wallet for transactions execution (well, +network fee).

**Describe alternatives you've considered**
Show only Free amount signa in Wallet, instead of sum of Commited+Free. 

**Additional context**
![image](https://user-images.githubusercontent.com/10243140/153729716-254fd27c-03ee-40d5-a99b-0fa5306e1c74.png)

**Comment by ohager** [comment]
Thanks for reporting... this is something I have on my radar. We are in MVP mode, and want to come out with NFT portal ASAP. Once beta is out I need to address several similar things, like more details on the Activity View for each transaction type. This issue fells into this category

**Comment by ohager** [comment]
btw: Thanks for exemplary reporting, considering your suggestions as enhancements and not bugs :clap:

**Comment by ohager** [comment]
available in 1.1.0
