### ISSUE TITLE
DApp Signing does not work

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-xt-wallet#19]
**Describe the bug**
When signing a transaction with a DApp, nothing happens

**To Reproduce**
1. e.g. Use Edit Profile on signum-art
2. Click on save
3. Nothing happens

**Expected behavior**
Should open a dialog and asking for confirmation

**Additional context**
First analysis shows a "NotFound" Error in the console coming from the extension/contentScript.

**Comment by rogerwim** [comment]
Wait, how did we break a core feature?

**Comment by ohager** [comment]
> Wait, how did we break a core feature?

Major refactoring.... but it's fixed, and was no issue of the wallet, but the signumjs library... all fine.
