### ISSUE TITLE
German translation is missing total amount

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet#2]
**Describe the bug**
In the german version the total amount is misisng..

**Expected behavior**
Should show "Gesamtbetrag" 
**Screenshots**
![grafik](https://user-images.githubusercontent.com/39116221/154704700-df99e720-8e70-474b-a689-9392d8383593.png)

**Browser (please complete the following information):**
Firefox

**Comment by ohager** [comment]
Note to myself: In english translation appears "Total Amount" correctly between the Payload and Button Section. Seems that there's an issue with the translations slugs
