### ISSUE TITLE
Wallet Connection with DApp does not work when having only one account registered

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-xt-wallet#20]
**Describe the bug**
When only one account is registered, i.e. right after installation and import and/or creation, the connection with a wallet does not work.

**To Reproduce**
1. Fresh Install and import or create _one_ account
2. Using a DApp to connect
3. Nothing happens

**Expected behavior**
Should open a confirmation window requesting for connection

**Additional context**

**Workaround**

As long as no patch is released, it is sufficient to create/import a second account, which triggers storing the accounts publickey.

**Solution**
After some debugging, I figured out that the initial account's publickey is not stored in local backend storage, which causes and `undefined` error while trying to fetch the current selected account on connection request. For that initial case, the related storage function has to be called.

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by ohager** [comment]
fixed
