### ISSUE TITLE
Showing wrong alias

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-xt-wallet#30]
**Describe the bug**
Clicking to change the address to alias show wrong alias.

**To Reproduce**
1 Create an account and register an alias to another address.
2 Import account to wallet XT
3 When toggling address to alias, alias is shown but the registered alias is for another address.

**Expected behavior**
Only show alias that leads to registered address

**Screenshots**
Tell me if needed

**Browser (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 100

**Additional context**

**Comment by ohager** [comment]
@deleterium as a user can have multiple alias, I always show the the first...but you are correct, need to check the alias for the related account. Thanks for reporting
