### ISSUE TITLE
add "Available Balance:" below Reserved Balance:

### ISSUE THREAD

**Issue by pir8radio** [signum-network/signum-xt-wallet#39]
![image](https://user-images.githubusercontent.com/16748696/178155822-0b4385b2-4a3a-48e9-8150-9b6a8aa3f892.png)

Just a small line below Reserved Balance that shows the unlocked available balance as a quick reference so we do not have to do the math to figure out what is available for transfer.

**Comment by ohager** [comment]
Will be like this:

in case has reserved (orders) and committed
![image](https://user-images.githubusercontent.com/3920663/178341724-c874101f-0e31-456e-9ea2-8a52915d1795.png)

only one:
![image](https://user-images.githubusercontent.com/3920663/178341921-664f80a6-cc75-4fba-adee-a1b93a358ce1.png)

nothing at all
![image](https://user-images.githubusercontent.com/3920663/178341825-2869dd09-382f-407a-96ad-d7a8c7659e75.png)

COmes with next release  this week
