### ISSUE TITLE
Add US Central to Node List

### ISSUE THREAD

**Issue by pir8radio** [signum-network/signum-xt-wallet#41]
https://us-central.signum.network/

**Comment by ohager** [comment]
@pir8radio If we add this as being a featured node then the cashbackId should be equal `8952122635653861124`

@frankTheTank72 Wdym?

**Comment by frankTheTank72** [comment]
I don´t think that the UK node is on this account

**Comment by pir8radio** [comment]
UK is not.   I thought node runner still received CB for running the node.  If that is not the case just let me know.  I'll think it through.

**Comment by frankTheTank72** [comment]
> UK is not. I thought node runner still received CB for running the node. If that is not the case just let me know. I'll think it through.

i think  CB is not needed to set to a special account

**Comment by frankTheTank72** [comment]
ah sorry i was always talking about the explorer not xt-wallet - but yes i think we can put the us-central also to the default node list @pir8radio / @ohager
