### ISSUE TITLE
Token Transfer not shown in preview tab

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-xt-wallet#44]
**Describe the bug**
Token Transfer has no preview when signing/confirming with XT

Raw data is available

**Expected behavior**
Having a preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/3920663/182865716-df19ca8e-1149-4432-92e2-408bf7451085.png)

![image](https://user-images.githubusercontent.com/3920663/182858124-7854b60d-d714-4db1-b22b-70363a011c4c.png)

**Comment by map1336** [comment]
Additionally, a custom feedback will be needed in case of sending to ``Burning address`` a.k.a ``Burning Token``
