### ISSUE TITLE
Load More button is not loading

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet#48]
**Describe the bug**
When I click on load more nothing happens.

**Expected behavior**
Next X trnasactions should be shown

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39116221/189288718-a116f32a-372f-4145-a946-f39a01247f3c.png)

**Browser (please complete the following information):**
 - Browser : Firefox, Chrome
 - Version XT-Wallert 1.2.3

**Additional context**

**Comment by ohager** [comment]
related to #49
