### ISSUE TITLE
Zoom at extension window

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-xt-wallet#5]
**Describe the bug**
I noticed that my extension was croping the edges, and some parts of text and buttons stayed outside the window. So I need to scroll to click "accept" or "decline". I think this is caused because my default zoom level at the browser is 130%. Investigating it I found that it is possible to zoom the text in extension window, but the window does not resize to fit the content.

**To Reproduce**
1. At any confirmation window, use Ctrl+mouse_scrool to zoom in an zoom out
2. Check that when zooming in, some content is rendered outside the window

**Expected behavior**
I expect one of two alternatives:
1. The zoom level at the extension windows is locked to 100%, so this does not happen
2. The extension window is resized to new size to fit the contents (even at first start if user has a default zoom level that is not 100%)

**Screenshots**
No need.

**Browser (please complete the following information):**
 - OS: GNU/Linux
 - Browser Firefox
 - Version 97.0

**Additional context**
None

**Comment by shefass** [comment]
I didn't knew that you can ctrl+mouse_scrool to zoom in an zoom out in extension.

**Comment by deleterium** [comment]
Strange, should not be allowed by "viewport user-scalable=no". ~~I would suggest to change the font size from px to vw, so zoom level does not mess font sizes, and a resized window will have a bigger text.~~

**Comment by deleterium** [comment]
I tried some tweaks with tailwind but setting text do variable size mess everything in fullscreen mode... So no more ideas in how to fix it. I would recommend just to open the window a bit bigger to acomodate small zoom changes and let the scroll bar there, if needed.
--edit
Another idea: When user click accept or decline, get the window size and store. Next time the confirmation window pops, use last size.

**Comment by shefass** [comment]
@deleterium  try editing http files directly https://github.com/signum-network/signum-xt-wallet/tree/develop/public

**Comment by ohager** [comment]
@deleterium I tested the zoom behavior in CHrome and FF. I preset a high zoom level in the browsers and opened the wallet in common popup mode.... all ok. I can scale inside, but works great on Chrome.

From your comment I assume you are referring to the Confirm Window. When having a zoomed Browser Window, the Popup just pops up at 100% scale. Of course, scaling within the popup window allows scaling also.

![scaling-firefox](https://user-images.githubusercontent.com/3920663/176190585-9cafcf6b-1e7e-4b89-a384-7ecc03da7918.gif)

To be honest: I do not see any need to work on a solution, as it all is controllable by the user. 

btw: Viewport no-user-scale seems to work for mobile only.

I'm willing to close this issue, as it seems to happen under very custom circumstances
