### ISSUE TITLE
Cannot send P2P message with 0 amount

### ISSUE THREAD

**Issue by shefass** [signum-network/signum-xt-wallet#51]
**Is your feature request related to a problem? Please describe.**
You cannot send p2p message with 0 amount, get error.

**Describe the solution you'd like**
If amount is 0 and there is message, use  /api?requestType=sendMessage , not regular /api?requestType=sendMoney

**Comment by ohager** [comment]
We have specific P2P messaging support for this.... closing.

![image](https://user-images.githubusercontent.com/3920663/194128312-6e85a03a-1f8c-4039-b855-8947f1a8d03c.png)
