### ISSUE TITLE
Transfer Alias Transaction is not being previewed

### ISSUE THREAD

**Issue by map1336** [signum-network/signum-xt-wallet#66]
**Is your feature request related to a problem? Please describe.**
As the title says when transferring an alias the transaction preview is missing when signing/confirming with XT.

**Additional context**
Technically,  an alias on private sale with 0 as price immediately transfers the alias to the receiver.

**Describe the solution you'd like**
Show the preview when transferring alias at the moment of signing/confirming a transaction.
![image](https://user-images.githubusercontent.com/35440957/223724286-485bb59f-5366-4698-85a0-9a1d171b5719.png)

**Comment by map1336** [comment]
This is the raw payload

```json
{
  "type": 1,
  "subtype": 6,
  "timestamp": 270559361,
  "deadline": 1440,
  "senderPublicKey": "6e1a0abea0cbacdc8c77a7de2868360d3e667b276a2f32bb847579d126d63e78",
  "recipient": "1673574549656521245",
  "recipientRS": "TS-LLJX-7YEQ-4C4S-3VFGG",
  "amountNQT": "0",
  "feeNQT": "1000000",
  "attachment": {
    "version.AliasSell": 2,
    "alias": "6442930183499063033",
    "priceNQT": "0"
  },
  "attachmentBytes": "02f99e1aa4dde269590000000000000000",
  "sender": "8929712165307955075",
  "senderRS": "TS-NFW5-WWDU-Y3BE-9P7VR",
  "height": 2147483647,
  "version": 2,
  "ecBlockId": "15654874362130940225",
  "ecBlockHeight": 522320,
  "cashBackId": "8952122635653861124",
  "verify": false,
  "requestProcessingTime": 2
}
```

**Comment by ohager** [comment]
this is actually the sell alias transaction... and I fixed it
