### ISSUE TITLE
In small window crops node address

### ISSUE THREAD

**Issue by shefass** [signum-network/signum-xt-wallet#7]
**Is your feature request related to a problem? Please describe.**
Then XT is in small window  "CONFIRM CONNECTION",at Networks section, node address is cropped.

**Describe the solution you'd like**
Show on next line

**Describe alternatives you've considered**
Length of node address can be checked and if bigger then x show on next line

**Additional context**
![image](https://user-images.githubusercontent.com/39196313/154057319-c89a4ff3-1e01-40a9-9e4c-6a12e33719ff.png)

**Comment by ohager** [comment]
fixed in 1.1.0
