### ISSUE TITLE
Adjust node list 

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet#78]
Please adjust the list if europe nodes accordently to the existing once :

![grafik](https://github.com/signum-network/signum-xt-wallet/assets/39116221/9fe494ec-dc9e-44d2-99ac-cdfb08ca87b2)

Europe
Europe1
Europe2
Europe3

Thanks

**Comment by map1336** [comment]
Imho, we should use this public resource list repo
https://github.com/signum-network/public-resources

So we prevent launching new versions any time a node needs to be `added/removed`

**Comment by frankTheTank72** [comment]
@ohager can we please adjust the list

**Comment by frankTheTank72** [comment]
@ohager can we please adjust the list

**Comment by frankTheTank72** [comment]
@ohager I think the europe3 is still missing

**Comment by frankTheTank72** [comment]
@ohager is this already published? Or is the release still in the making? Thanks
