### ISSUE TITLE
Add explorer link to wallet address

### ISSUE THREAD

**Issue by rever273** [signum-network/signum-xt-wallet#9]
Just add a little arrow near wallet address so we can use explorer
![Без имени-1](https://user-images.githubusercontent.com/77928665/153845880-33cfeb1c-0586-40a6-8818-2d338a4b7d91.png)

Roman273#0506

**Comment by ohager** [comment]
Ok. Mind that, if an account owns an alias it will be shown there also... 

![image](https://user-images.githubusercontent.com/3920663/154077825-ef56debf-7610-4eee-b382-95d534c5cf5e.png)

**Comment by ohager** [comment]
available in 1.1.0
